### ISSUE TITLE
Is there documentation and source for the python scripts?

### ISSUE THREAD

**Issue by Tman3** [singhal/popgen_tutorial#1]
I noticed that there are few python scripts used in the tutorial, e.g., 
vcf_to_phy.py --infile Massoko_Dryad_VCF_final_subset_noIndels_maf05_thinned1K.vcf.gz 
vcf_to_geno.py

Do you know where I can locate them as I would like to follow your tutorial?

**Comment by singhal** [comment]
I added the Python scripts to the repo, but I don't have much documentation because they were just used internally. I hope that helps!
