### ISSUE TITLE
Ask about two EIG parameter files: Massoko_smartpca.par and convert.par

### ISSUE THREAD

**Issue by biomichal** [singhal/popgen_tutorial#3]
Hi,
Thank you for your sharing pop_gen tutorial. 
When I follow the steps, I can not find two EIG prmeter files:  Massoko_smartpca.par and convert.par, as in the next two command in the toturial.
```
EIG-6.1.3/bin/convertf -p convert.par
~/EIG-6.1.3/bin/smartpca -p Massoko_smartpca.par > Massoko_smartpca.out
```
So, can you share these two files? 
Thank you.

**Comment by singhal** [comment]
I've uploaded them. thanks!

**Comment by biomichal** [comment]
Thanks
